mappings = {
    'AccruedCommissions': {
        'json_key': 'НачисленныеКомиссии',
        'mapping': {
            'period': 'Период',
            'date': 'Дата',
            'number': 'Номер',
            'type_': 'Вид',
            'tariff': 'Тариф',
            'amount': 'Сумма',
            'registrar': 'Регистратор',
        }
    },
    'RepoDocuments': {
        'json_key': 'ДокуметыРЕПО',
        'mapping': {
            'passport': 'Паспорт',
            'order_info': 'Заказ',
            'document': 'Документ',
            'deal_type': 'ВидСделки',
            'number': 'Номер',
            'date': 'Дата',
            'currency': 'Валюта',
            'market': 'Рынок',
            'isin': 'ISIN',
            'ticker': 'Тикер',
            'financial_instrument': 'ФинансовыйИнструмент',
            'settlement_date': 'ДатаРасчетов',
            'opening_date': 'ДатаОткрытия',
            'closing_date': 'ДатаЗакрытия',
            'order_date': 'ЗаказДата',
            'order_number': 'ЗаказНомер',
            'opening_price': 'ЦенаОткрытия',
            'closing_price': 'ЦенаЗакрытия',
            'quantity': 'Количество',
            'interest_rate': 'Доходность',
            'accrued_interest': 'НКД',
            'opening_amount': 'СуммаОткрытия',
            'closing_amount': 'СуммаЗакрытия',
            'order_opening_number': 'НомерЗаявкиОткрытия',
            'kase_order_number': 'НомерЗаявкиНаКАСЕ',
            'market_type': 'ВидРынка',
            'exchange_type': 'ТипРынка',
            'execution_status': 'СтатусИсполнения',
            'transaction_method': 'МетодПроведенияСделок',
        }
    },
    'TradeDocuments': {
        'json_key': 'ДокументыПокупкаПродажа',
        'mapping': {
            'passport': 'Паспорт',
            'order_info': 'Заказ',
            'document': 'Документ',
            'deal_type': 'ВидСделки',
            'number': 'Номер',
            'date': 'Дата',
            'currency': 'Валюта',
            'market': 'Рынок',
            'isin': 'ISIN',
            'ticker': 'Тикер',
            'financial_instrument': 'ФинансовыйИнструмент',
            'settlement_date': 'ДатаРасчетов',
            'opening_date': 'ДатаОткрытия',
            'closing_date': 'ДатаЗакрытия',
            'order_date': 'ЗаказДата',
            'order_number': 'ЗаказНомер',
            'price': 'Цена',
            'quantity': 'Количество',
            'interest_rate': 'Доходность',
            'accrued_interest': 'НКД',
            'amount': 'Сумма',
            'closing_amount': 'СуммаЗакрытия',
            'opening_order_number': 'НомерЗаявкиОткрытия',
            'kase_order_number': 'НомерЗаявкиНаКАСЕ',
            'market_type': 'ВидРынка',
            'exchange_type': 'ТипРынка',
            'swap': 'SWOP',
            'currency_market': 'ВалютныйРынок',
            'execution_status': 'СтатусИсполнения',
            'transaction_method': 'МетодПроведенияСделок',
        }
    },
    'FinancialInstrumentsMovement': {
        'json_key': 'ДвижениеФИ',
        'mapping': {
            'financial_instrument': 'ФинансовыйИнструмент',
            'account_number': 'ЛицевойСчет',
            'opening_balance': 'КоличествоНачальныйОстаток',
            'closing_balance': 'КоличествоКонечныйОстаток',
            'turnover': 'КоличествоОборот',
            'amount_in': 'КоличествоПриход',
            'amount_out': 'КоличествоРасход',
            'issuer': 'Эмитент',
            'currency_of_issue': 'ВалютаВыпуска',
            'type_of_security': 'ВидЦБ',
            'fair_price': 'СправедливаяЦена',
            'ISIN': 'ИСИН',
            'sum_in_kzt': 'СуммаKZT',
            'ticker': 'Тикер',
        }
    },
    'MoneyMovement': {
        'json_key': 'ДвижениеДенег',
        'mapping': {
            'bank_account': 'БанковскийСчет',
            'currency': 'Валюта',
            'account_number': 'НомерСчета',
            'closing_balance': 'СуммаКонечныйОстаток',
            'opening_balance': 'СуммаНачальныйОстаток',
            'money_in': 'СуммаПриход',
            'money_out': 'СуммаРасход',
        }
    }
}
